### ISSUE TITLE
Netflix avatars URL change

### ISSUE THREAD

**Issue by nirewen** [nirewen/discord-netflix#31]
Recently all the avatars URLs changed, and, since my app's assets is based in their name (specifically the end of it), it's impossible to get the avatars from the asset list now.

I don't know if that's just for now, or it's a thing that happens eventually so all the URLs change in the middle of the night.

I could rename them all again manually as I did before, but if it happens again, how long will I have to do this?

So, I need help on finding a better way to index all the avatars, by name, by some form of ID, I don't know. Ideas are appreciated.

Calling contributors @NovusTheory @Wist9063 @Keyygan

**Comment by NovusTheory** [comment]
After a bit of reverse engineering. I've come to a conclusion that _may_ be the best way to do it. I've looked at the Netflix API and it seems like something they shouldn't change anytime soon as it's their way of leading back to a hash (the thing you're using right now to fetch avatars).

Here's what you could look into or I can personally look into it and PR it.

Netflix has `window.netflix` which provides useful information to you. It is possible to grab the current profile data by doing `window.netflix.reactContext.models.userInfo`. This will provide you with a very important detail which is a user UUID (for example their UUID is `FWE87WG5WAF`. You can use this UUID to fetch any information associated with the current user (profile). To grab a UUID (supposedly) of the avatar they currently have you can do `window.netflix.falcorCache.profiles.FWE87WG5WAF.avatar.value.2`. `avatar.value` is an object and `value.2` is the supposed avatar ID Netflix gave this avatar.

The structure of the avatar ID is `AVATAR|UUID_YOU_PROBABLY_WANT|en|US|some_id?` and this is given as a string so you'll need to string match the ID out.
**Important note: **The structure of the avatar ID _may_ be different for the legacy icons and those will be `iconNUM` e.g. `icon1` - `icon23`. This seems to possibly apply to older profile accounts where the API on Netflix seems to return this specific avatar ID rather than their new UUID system.

Hope this information helps to aid in being able to keep a persistent id that Netflix won't change. If you'd like to find the ID's for everything you can go to the edit profile page and inspect element all the icons and inside the `data-ui-tracking-context` attribute is a URI encoded value which contains the avatar name. (This data may not apply to the legacy `iconNUM`)

**Comment by nirewen** [comment]
I think I shouldn't rely on window.netflix. 

I tried that before, but window.netflix is not always there. 
Sometimes it is, sometimes it's not. 
Back in the beta of the app, I used this system of video ID to grab the name of the episode, season, etc ([see L35](/discord-netflix/blob/master/main.js#L35) where id is defined but never used), but when I built the app sent it to my friends, window.netflix wasn't there in their app, so the app and the Rich Presence were not working. 

That's why I get the element content instead of get from the _API_

**Comment by NovusTheory** [comment]
I'm not sure if this API changes with region or other factors such as not being able to run a SPA (but the app is Chrome version 60+ which is fully capable of running SPA).
. 
Besides not relying on the API I'm not sure there is much you can do. Hashes are hashes and they _will_ change. Usually hashes only change if they update the file which changes the hash of the file then. I'm not sure there is a way to avoid not using the API at this point. Based on what Netflix is doing it seems almost impossible now to get their profile avatar without using the API. I'm making a conclusion that `window.netflix` should always be present in the app. Maybe you were trying to use the API before it was loaded in as this is a SPA app and everything loads dynamically. If it truly was not there then I'd like to possibly get more insight on that and if I could replicate (force Netflix) to provide me with a webpage that doesn't contain the API I could investigate alternative ways of fetching the avatar.

**Comment by nirewen** [comment]
I think I'll make use of the API. If it indeed loads later when using the app, the avatar should appear normally.

**Comment by PassTheMayo** [comment]
Any ETA for when this will be released? It's been 24 days since last comment and I still don't see any avatars in the Rich Presence.

**Comment by Wist9063** [comment]
anyone got a PR yet?

**Comment by NovusTheory** [comment]
I have not worked on this at all. If anyone wants to grab it or I could I guess.
