### ISSUE TITLE
ERROR UI3010

### ISSUE THREAD

**Issue by CroagSenpai** [nirewen/discord-netflix#35]
It does not load any series / movie and I get that error

**Comment by NovusTheory** [comment]
According to Netflix, "If you experience the error code UI3010 on your computer, it typically points to information stored on your browser that needs to be refreshed, or to a network connectivity issue. Follow the troubleshooting steps below to resolve the issue."

I'll assume the issue is not with a network connectivity so you could optionally clear the data in the app to see if that resolves the issue.

On Windows it would be under **%appdata%/Netflix/Cache** and delete the folder

**Comment by CroagSenpai** [comment]
Thanks :)

**Comment by CroagSenpai** [comment]
only 480p in the app?

**Comment by NovusTheory** [comment]
The resolution of a video is solely based on your internet connection / what you can handle

**Comment by nirewen** [comment]
Increase your internet speed or [decrease the videos resolution](https://www.netflix.com/HdToggle).
