### ISSUE TITLE
Scrobble to traktv

### ISSUE THREAD

**Issue by metehus** [nirewen/discord-netflix#43]
Use the Trak tv api to scrobble the watching show/movie in netflix

**Comment by nirewen** [comment]
Elaborate

**Comment by metehus** [comment]
In [traktv api](https://trakt.docs.apiary.io/#reference/scrobble) you can scrobble a show/movie that you can send progress if its playing, paused or stopped, You can use this to scrobble to an traktv account the show/movie you are watching, this isnt a discord and netflix but it can be a good idea

**Comment by DooMl** [comment]
It must be done in like another repository, as because of this : 
https://support.trakt.tv/forums/188762-general/suggestions/6170487-sync-trakt-and-netflix

> Justin Nemeth (Founder, trakt) commented  ·  May 1, 2018 7:39 AM  ·  Flag as inappropriate

I wish we could do more with Netfix, but they don't have a public API or way to get your data out. There is a chrome plugin that is trying to get around this, but its tough since its using non standard ways around the limitations Netflix has in place.
