### ISSUE TITLE
Picture On Discord

### ISSUE THREAD

**Issue by HorizonTMP** [nirewen/discord-netflix#6]
Hi There,

I use a "Watch Together" profile on my Netflix account and that does not show the Logo or the profile picture on Discord.

For Example: 
When using a normal profile - https://i.imgur.com/LIQguqK.png
When using a Watch Together profile - https://i.imgur.com/NCxpbdh.png

I did not know if this was intentional or a bug. Cheers :)

**Comment by nirewen** [comment]
I would need a Watch Together profile in order to add this. It seems like a beta feature I don't have, as discussed [here](https://www.reddit.com/r/netflix/comments/4v17ji/us_watch_together_profile_added_to_account/).
I'll try to find a hack or, if you can give me the URL of the image, I can see if it fits the other ones and I can add it to the application assets as well.

**Comment by HorizonTMP** [comment]
Sure, 

The image url is https://assets.nflxext.com/ffe/profiles/avatars_v2/320x320/PICON_038.png

Thanks

**Comment by nirewen** [comment]
Done!
I even uploaded PICON_037
Should work now. You don't need to update the app, or install it again. Because the way I made it, should work without any problem.
I don't know why they jumped from 29 to 37 like that 😕 
![image](https://user-images.githubusercontent.com/8761479/37670153-60effd40-2c47-11e8-881a-869c00f5248d.png)

**Comment by HorizonTMP** [comment]
https://i.imgur.com/GysN0s6.png

I can confirm it is working :)

Thanks
